### ISSUE TITLE
Add a silent option

### ISSUE THREAD

**Issue by hiroppy** [iampava/imagemin-webp-webpack-plugin#13]
Hi, I want to use this plugin but `console.log` outputs as a default.

code: https://github.com/iampava/imagemin-webp-webpack-plugin/blob/master/plugin.js#L74-L82

I'll use this plugin on CLI tool, so I want to turn off it.

Would you consider turning off `console.log`?
Thanks.

**Comment by iampava** [comment]
Hey, 

Good idea! Just published v3.2.1 with these changes. 
Cheers!

**Comment by hiroppy** [comment]
Thank you for your quick response!
