### ISSUE TITLE
Heroku support?

### ISSUE THREAD

**Issue by clieee** [iampava/imagemin-webp-webpack-plugin#16]
Hello,

I'm experiencing issues when using this plugin on Heroku platform. It works fine locally (Docker, node-alpine). Some images are converted, but some are not. All I'm getting in the log is ```imagemin-webp-webpack-plugin: 76 images failed to convert to webp```  

Any ideas?

**Comment by clieee** [comment]
Found out that the correct version of ```lib-png``` was not installed. Using ```Aptfile``` in order to install it first on the machine, then the conversion was working as expected.

**Comment by iampava** [comment]
Glad you fixed it, although it's a little bit cause I once tested it on Heroku and I didn't need to do any special things :-?
