### ISSUE TITLE
Force creating a WebP file

### ISSUE THREAD

**Issue by TheodorTomas** [iampava/imagemin-webp-webpack-plugin#3]
Do you want to request a feature or report a bug?

Possible bug/Feature idea

What is the current behaviour?

If the resulting WebP file is the same size as the original file the plugin does not create a WebP file.

What is the expected behaviour?

Should create a WebP file for each image matching the RegExp. This should possibly be optional by configuring the plugin with a force = true boolean. Otherwise it should be the default behaviour.

Example:

config: [{
              test: /\.(jpe?g)$/,
              options: {
                quality: 80,
                force: true
              }
            }, {
              test: /\.(png)$/,
              options: {
                lossless: true,
                force: true
              }
            }],

**Comment by iampava** [comment]
Hey and thanks for contributing to this project :)

Can you give me an image which is the same size when converted to WebP, so that I can test the behavior and fix the bug?

**Comment by iampava** [comment]
Oh snap... I was hoping it's a mistake on my side and not in the dependencies. I see that `imagemin` has a PR fixing this issue but it's not been merged yet: https://github.com/imagemin/imagemin/pull/285

**Comment by TheodorTomas** [comment]
Nice job finding a PR relating to this. Their code review process is quite extensive, I am not going to hold my breath waiting to get his merged. :P
I will have to add a a small hack to accommodate this issue in the meantime, but I hope this gets resolved soon.

**Comment by iampava** [comment]
Hmm... now that I think about it I guess I could add a log message telling you if any of your images didn't get converted. This way, when you make the build you'll know if something went wrong

**Comment by iampava** [comment]
Added this enhancement covering the change. I'm gonna take care of it on Friday ;) 

https://github.com/iampava/imagemin-webp-webpack-plugin/issues/4

**Comment by iampava** [comment]
Released version 2.0.0 with the added feature

**Comment by TheodorTomas** [comment]
Hey @iampava, The PR fixing the root of this issue has been merged. I believe this should no longer be a problem in the newest version of "imagemin". PR: https://github.com/imagemin/imagemin/commit/744a6c29415c8e46f5800f9fcb7380fb82c48286

**Comment by iampava** [comment]
Nice! Bumped up the dependency version. Will be in the next release, as soon as I fix https://github.com/iampava/imagemin-webp-webpack-plugin/issues/6

**Comment by iampava** [comment]
Published v3.0.0 on NPM!
