### ISSUE TITLE
Low severity vulnerabilities on yargs-parser after installation

### ISSUE THREAD

**Issue by wilbertcaba** [iampava/imagemin-webp-webpack-plugin#32]
I get a warning from NPM Audits since 4 low severity vulnerabilities of **Prototype Pollution** are found in the package `yargs-parser` after installation which need manual review.

I've never gone into any packacge.json file and arbitrarily bump versions, since I don't have vast knowledge on the matter and don't know if doing so could represent a breaking change.

Could you point me on the right direction? How could this be resolved?

**Comment by iampava** [comment]
Thanks for that. I updated the packages, which fixed most of the vulnerabilities. There are still 6 left, but you shouldn't worry about that because they're used in `/test-project` which is not actually used in the final plugin.

These changes are now published in `v3.3.3`.
