### ISSUE TITLE
GIF support using gif2webp

### ISSUE THREAD

**Issue by bartdecorte** [iampava/imagemin-webp-webpack-plugin#35]
I recently stumbled upon the gif2webp utility, which is capable of converting animated gifs to webp images. I've done some research and found an imagemin-gif2webp package right here: [https://github.com/imagemin/imagemin-gif2webp](https://github.com/imagemin/imagemin-gif2webp).

Seems to me support could be integrated fairly easy. Are there any plans to support this in the near feature?

**Comment by iampava** [comment]
Sweet! Would love to add this to the package. Will try and take a look next weekend, when I hope I'll have some free time.

If you wanna do a PR in the meantime, it would be much appreciated.

**Comment by bartdecorte** [comment]
Looks like we’ll have to wait that out, can’t merge this if it does not work on Windows. Could not test that myself, I’m a Mac guy 😄.
