### ISSUE TITLE
Add an option to replace images and webpack entries, instead of keeping originals

### ISSUE THREAD

**Issue by blephy** [iampava/imagemin-webp-webpack-plugin#37]
Hi,

I'm using this plugin for my PWA. Problem is that when i use this plugin, it keep original files and send them to the build folder, and when i run workbox utility to make my service worker precaching, it precache both .png and .webp.

I cannot turn around with globPattern to exclude .png from my precaching because i have some .png loaded by the manifest and html webpack plugin (the favicon ...).

Furthermore, if i put this plugin under html webpack plugin, it will make a favicon.webp but do not replace the favicon entry, causing html webpack plugin to integrate the favicon.png instead of favicon.webp.

The resulting is that i have .webp nicely in my build folder, but my app do not target them ...

I don't understand how people use this plugin as it do not replace images webpack entries in the build process.

What i need, is that plugin replace images without sending originals, and replace the original entries in webpack, making the application target on webp format.

**Comment by iampava** [comment]
Hey!

It's intended to keep the original images as `webp` is not supported everywhere. The correct way to use it is via the `<picture>` element and letting the browser choose the best format.

Regarding your problem I can think of 2 solutions:

1. Maybe move all images that are intended to be used only as WebP inside a special folder and using globPatterns ignore everything else from there
2. Write your own service-worker to have full control of the assets you save and when. Tbh I always wrote my own SWs, and once you do it once you can pretty much copy-paste them between projects.

**Comment by blephy** [comment]
I swapped to responsive-loader, i thinks it's a better solution for me.

Thanks for your response ;)

**Comment by iampava** [comment]
Cool! All the best 💪
