### ISSUE TITLE
Append ".webp" to [filename] + [extension] instead of replacing extension

### ISSUE THREAD

**Issue by TheodorTomas** [iampava/imagemin-webp-webpack-plugin#8]
Do you want to request a feature or report a bug?

Possible bug/Feature idea

What is the current behaviour?

Replaces extension to "webp" format.

"checkmark-icon.jpg" => "checkmark-icon.webp"

What is the expected behaviour?

Append ".webp" to [filename] + [extension] to ensure uniqueness. This would prevent files with same name but different extensions overwriting the output of the .webp conversion output.

Example:

"checkmark-icon.jpg" => "checkmark-icon.jpg.webp"
"checkmark-icon.png" => "checkmark-icon.png.webp"

**Comment by iampava** [comment]
Hey,

I get your point but I don't think this is an issue that should be handled by the plugin. I mean, why would you have the same image in different formats? In what use case would you use both?

**Comment by kelly-tock** [comment]
I know this is old, but just a quick comment, you may want to have a fallback jpg for older browsers, but just the extension change should be fine.
